# Generated by Django 4.1 on 2022-09-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=55, null=True)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('duration', models.DurationField()),
                ('event', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
