# Generated by Django 4.1 on 2022-09-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('designation', models.CharField(max_length=255)),
                ('detail', models.TextField()),
            ],
        ),
    ]
