# Generated by Django 4.1 on 2022-09-09 09:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmgAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('work_status', models.CharField(blank=True, choices=[('Completed: Application for work already done', 'Com'), ('In Progress: Application for work in progress or is planned in the immediate future', 'InPro')], max_length=255, null=True)),
                ('apply_type', models.CharField(blank=True, choices=[('Individual', 'Ind'), ('Organization', 'Org')], max_length=255, null=True)),
                ('nomination_type', models.CharField(blank=True, choices=[('Self', 'S'), ('Nominating Other', 'O')], max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None, unique=True)),
                ('website', models.TextField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('org_type', models.CharField(blank=True, max_length=255, null=True)),
                ('org_name', models.CharField(blank=True, max_length=255, null=True)),
                ('org_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('org_person_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('org_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('org_person_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None)),
                ('org_address', models.CharField(blank=True, max_length=255, null=True)),
                ('org_web', models.TextField(blank=True, max_length=255, null=True)),
                ('work_exp', models.TextField(blank=True, null=True)),
                ('interpretation', models.TextField(blank=True, max_length=300, null=True)),
                ('climate_change_challenge', models.TextField(blank=True, null=True)),
                ('award_category', models.CharField(blank=True, choices=[('Only avoid', 'a'), ('Only Minimize', 'm'), ('Only Generate', 'g'), ('Avoid and Minimize', 'a&m'), ('Avoid,Minimize and Generate', 'a,m&g')], max_length=255, null=True)),
                ('target_status', models.CharField(blank=True, max_length=255, null=True)),
                ('target_completed', models.TextField(blank=True, null=True)),
                ('ongoing_invitation_summary', models.TextField(blank=True, null=True)),
                ('invitation_summary', models.TextField(blank=True, null=True)),
                ('challenge_in_invitation', models.TextField(blank=True, null=True)),
                ('implement_invitation', models.TextField(blank=True, null=True)),
                ('amg_image_before', models.ImageField(blank=True, null=True, upload_to='images/awards_forms/')),
                ('amg_image_after', models.ImageField(blank=True, null=True, upload_to='images/awards_forms/')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/awards_forms/')),
            ],
        ),
        migrations.CreateModel(
            name='ClimateAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None, unique=True)),
                ('org_college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_one', models.TextField(blank=True, null=True)),
                ('address_line_two', models.TextField(blank=True, null=True)),
                ('address_landmark', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField()),
                ('brief_description', models.TextField(blank=True, max_length=100, null=True)),
                ('working_video', models.FileField(upload_to='images/awards_forms/')),
                ('major_climate_challenge', models.TextField(blank=True, null=True)),
                ('steps', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AwardSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('participants', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('submit_by_participants', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('evaluation', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('reward', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('guidelines', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('award_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_type', to='awards.award')),
            ],
        ),
    ]
