# Generated by Django 4.1 on 2022-09-05 05:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_rename_award_amgaward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/awards')),
            ],
        ),
        migrations.CreateModel(
            name='ClimateHackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('participants', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('submit_by_participants', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('evaluation', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('reward', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('guidelines', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
