# Generated by Django 4.1 on 2022-09-05 06:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_award_climatehackathon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('participants', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('submit_by_participants', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('evaluation', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('reward', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('guidelines', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('award_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_type', to='awards.award')),
            ],
        ),
        migrations.DeleteModel(
            name='ClimateHackathon',
        ),
    ]
