# Generated by Django 4.1 on 2022-09-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_awardsubcategory_delete_climatehackathon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amgaward',
            old_name='interpretetion',
            new_name='interpretation',
        ),
        migrations.RenameField(
            model_name='amgaward',
            old_name='target_complated',
            new_name='target_completed',
        ),
        migrations.RemoveField(
            model_name='amgaward',
            name='amg_image',
        ),
        migrations.AddField(
            model_name='amgaward',
            name='amg_image_after',
            field=models.ImageField(blank=True, null=True, upload_to='images/awards_forms/'),
        ),
        migrations.AddField(
            model_name='amgaward',
            name='amg_image_before',
            field=models.ImageField(blank=True, null=True, upload_to='images/awards_forms/'),
        ),
        migrations.AlterField(
            model_name='award',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/awards_forms/'),
        ),
    ]
