# Generated by Django 4.1 on 2022-09-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_rename_interpretetion_amgaward_interpretation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amgaward',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amgaward',
            name='challenge_in_invitation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amgaward',
            name='implement_invitation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amgaward',
            name='interpretation',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='amgaward',
            name='invitation_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amgaward',
            name='ongoing_invitation_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amgaward',
            name='target_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amgaward',
            name='target_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
