# Generated by Django 4.1 on 2022-09-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_alter_amgaward_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amgaward',
            name='id',
        ),
        migrations.AddField(
            model_name='amgaward',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amgaward',
            name='email',
            field=models.EmailField(blank=True, default=True, max_length=254, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
